### ISSUE TITLE
REFACTOR ApproachesTableJPanel

### ISSUE THREAD

**Issue by Jorn-Steehouder** [Svennett/HUSACCT_FOR_REFACTORING#34]
#### Extract method/class
- IniutUI (**190 regels code**) (ApproachesTableJPanel)
   - Creeeren van tabpane met daarin de tabs
   - iedere tab aparte klasse
      - De eerste twee tabs worden nu ook opgebouwd binnen de initUI

#### (Re)move class
ApproachesTableJpanel (De tabbedPane met daarin de opbouw van de distinct en allapproaches):
- Deze klasse heeft ten eerste een verkeerde naam aangezien mojo er ook in zit.
- De logica kan beter in de ReconstructJPanel komen.

#### Move buttons en hun logica
Sommig buttons die op ReconstructJPanel staan, zijn erg afhankelijk van op welke tab je momenteel zit. De buttons moeten eigenlijk op de tab zelf neergezet worden.

#### AllApproachesJPanel
Hierin komt de opbouw van de allApproachesTab.
De initUI methode van deze klas bevat na het verplaatsen nog te veel dus is er een extract method uitgevoerd. Hierbij zijn de volgende methodes ontstaan:
- setupAllApproachesTable
   - Hierin wordt alleen de approaches tabel opgezet
- setAllApproachesScrollPane
   - Hierin wordt de dimensie van de approaches tabel geset en voegt het automatisch een scroll toe wanneer het te groot is
- setupAllApproachesParameterTable
   - Hierin wordt alleen de parameter tabel opgezet
- setupAllApproachesParameterScrollPanel
   - Hierin wordt de dimensie van de parameter tabel geset en voegt het automatisch een scroll toe wanneer het te groot is
- setSelectionListener
   - Deze geöverride methode is verplaatst naar een andere klasse (**ApproachesTableSelectionListener**)
- new METHOD: setupButtonPanel
   - Hier worden de buttons aangemaakt voor de allapproaches panel
- new METHOD: actionperformed van de buttons
   - Hier staan de acties die gekoppeld zijn aan buttons

#### DistinctApproachesJPanel
Hierin komt de opbouw van de disinctApproachesTab.
De initUI methode van deze klas bevat na het verplaatsen nog te veel dus is er een extract method uitgevoerd. Hierbij zijn de volgende methodes ontstaan:
- setupDistinctApproachesTable
   - Hierin wordt alleen de distinct approaches tabel opgezet
- setDistinctApproachesScrollPane
   - Hierin wordt de dimensie van de distinct approaches tabel geset en voegt het automatisch een scroll toe wanneer het te groot is
- new METHOD: setupButtonPanel
   - Hier worden de buttons aangemaakt voor de distinctapproaches panel
- new METHOD: actionperformed van de buttons
   - Hier staan de acties die gekoppeld zijn aan buttons

#### ApproachesTableSelectionListener
Deze Listener is alleen bestemd voor de allApproachesJPanel. Deze klasse bevat namelijk een methode die de parameter tabel vult met waardes.

#### ReconstructJPanel
De initUI van ApproachesTableJPanel(Na het refactoren) wordt een aparte methode in ReconstructJPanel. Hierdoor vervalt ApproachesTableJPanel aangezien al de logica verplaatst is naar andere klassen.
De initUI bevatte eerst 190 regels code zoals eerde vermeld is. Nu daarentegen bevat deze methode maar 8 regels (witregels weggelaten) en is nu veel beter leesbaar.

**Comment by Svennett** [comment]
issue is resolved
